name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "{% if project_path_python %}{{ project_path_python }}/{% endif %}pyproject.toml"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install Project
        run: make install

      - name: Run checks
        run: make check
