name: Docs

on: [push, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - uses: actions/setup-node@v5
      with:
        node-version: 18

    - run: npm install -g @mermaid-js/mermaid-cli

    - name: Install Project
      run: make install

    - name: Generate Docs
      run: make docs

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v4
      if: {{ "${{ github.event_name == 'workflow_dispatch' }}" }}
      with:
        publish_branch: gh-pages
        github_token: {{ "${{ secrets.GITHUB_TOKEN }}" }}
        publish_dir: docs/html/
        force_orphan: true
