##############################################################################
# THIS FILE IS GENERATED BY MXMAKE
#
# SETTINGS (ALL CHANGES MADE BELOW SETTINGS WILL BE LOST)
##############################################################################

## core.venv

# Python interpreter to use for creating the virtual environment.
# default: python3
PYTHON_BIN?=python3

# Minimum required Python version.
# default: 3.7
PYTHON_MIN_VERSION?=3.7

# Whether to use a VENV or not; "true" or "false".
# default: true
VENV_CREATE?=true

# The folder where the virtual environment get created.
# default: venv
VENV_FOLDER?=venv

# mxdev to install in virtual environment.
# default: https://github.com/mxstack/mxdev/archive/main.zip
MXDEV?=https://github.com/mxstack/mxdev/archive/main.zip

# mxmake to install in virtual environment.
# default: https://github.com/mxstack/mxmake/archive/develop.zip
MXMAKE?=-e .

## core.files

# The config file to use.
# default: mx.ini
PROJECT_CONFIG?=mx.ini

# Target folder for generated scripts.
# default: $(VENV_SCRIPTS)
SCRIPTS_FOLDER?=$(VENV_FOLDER)/bin

# Target folder for generated config files.
# default: cfg
CONFIG_FOLDER?=cfg

## core.test

# The command which gets executed. Defaults to the location the
# :ref:`run-tests` template gets rendered to if configured.
# default: $(SCRIPTS_FOLDER)/run-tests.sh
TEST_COMMAND?=$(VENV_FOLDER)/bin/python -m mxmake.tests

# Additional make targets the test target depends on.
# no default value

TEST_DEPENDENCY_TARGETS?=

## core.coverage

# The command which gets executed. Defaults to the location the
# :ref:`run-coverage` template gets rendered to if configured.
# default: $(SCRIPTS_FOLDER)/run-coverage.sh
COVERAGE_COMMAND?=$(VENV_FOLDER)/bin/coverage run -m mxmake.tests

## core.clean

# Space separated list of files and folders to remove.
# no default value

CLEAN_TARGETS?=dist mxmake.egg-info

## core.docs

# The Sphinx build executable.
# default: $(VENV_SCRIPTS)sphinx-build
DOCS_BIN?=$(VENV_FOLDER)/bin/sphinx-build

# The Sphinx auto build executable.
# default: $(VENV_SCRIPTS)sphinx-autobuild
DOCS_AUTOBUILD_BIN?=$(VENV_FOLDER)/bin/sphinx-autobuild

# Documentation source folder.
# default: docs/source
DOCS_SOURCE_FOLDER?=docs/source

# Documentation generation target folder.
# default: docs/html
DOCS_TARGET_FOLDER?=docs/html

# Documentation Python requirements to be installed (via pip).
# no default value

DOCS_REQUIREMENTS?=sphinx-conestack-theme myst-parser

## core.system-dependencies

# Space separated system package names.
# no default value

SYSTEM_DEPENDENCIES?=

##############################################################################
# END SETTINGS - DO NOT EDIT BELOW THIS LINE
##############################################################################

##############################################################################
# Makefile for mxmake projects.
##############################################################################

# Defensive settings for make: https://tech.davis-hansson.com/p/make/
SHELL:=bash
.ONESHELL:
# for Makefile debugging purposes add -x to the .SHELLFLAGS
.SHELLFLAGS:=-eu -o pipefail -O inherit_errexit -c
.SILENT:
.DELETE_ON_ERROR:
MAKEFLAGS+=--warn-undefined-variables
MAKEFLAGS+=--no-builtin-rules

# Sentinel files
SENTINEL_FOLDER?=.mxmake-sentinels
SENTINEL?=$(SENTINEL_FOLDER)/about.txt
$(SENTINEL):
	@mkdir -p $(SENTINEL_FOLDER)
	@echo "Sentinels for the Makefile process." > $(SENTINEL)

##############################################################################
# venv
##############################################################################

VENV_SCRIPTS=

# determine the VENV
ifeq ("${VENV_CREATE}", "true")
	VENV_SCRIPTS=${VENV_FOLDER}/bin/
else
# given we have an existing venv folder, we use it, otherwise expect scripts
# in system PATH.
	ifneq ("${VENV_FOLDER}", "")
		VENV_SCRIPTS=${VENV_FOLDER}/bin/
	endif
endif

# Check if given Python is installed?
ifeq (, $(shell which $(PYTHON_BIN) ))
  $(error "PYTHON=$(PYTHON_BIN) not found in $(PATH)")
endif

# Check if given Python version is ok?
PYTHON_VERSION_OK=$(shell $(PYTHON_BIN) -c "import sys; print((int(sys.version_info[0]), int(sys.version_info[1])) >= tuple(map(int, '$(PYTHON_MIN_VERSION)'.split('.'))))")
ifeq ($(PYTHON_VERSION_OK),0)
  $(error "Need Python >= $(PYTHON_MIN_VERSION)")
endif

VENV_TARGET:=$(SENTINEL_FOLDER)/venv.sentinel
$(VENV_TARGET): $(SENTINEL)
	@echo "Setup Python Virtual Environment under '$(VENV_FOLDER)'"
	@$(PYTHON_BIN) -m venv $(VENV_FOLDER)
	@$(VENV_SCRIPTS)pip install -U pip setuptools wheel
	@$(VENV_SCRIPTS)pip install -U $(MXDEV)
	@$(VENV_SCRIPTS)pip install -U $(MXMAKE)
	@touch $(VENV_TARGET)

.PHONY: venv
venv: $(VENV_TARGET)

.PHONY: venv-dirty
venv-dirty:
	@rm -f $(VENV_TARGET)

.PHONY: venv-clean
venv-clean: venv-dirty
	@rm -rf $(VENV_FOLDER)

##############################################################################
# files
##############################################################################

# set environment variables for mxmake
define set_files_env
	@export MXMAKE_VENV_FOLDER=$(1)
	@export MXMAKE_SCRIPTS_FOLDER=$(2)
	@export MXMAKE_CONFIG_FOLDER=$(3)
endef

# unset environment variables for mxmake
define unset_files_env
	@unset MXMAKE_VENV_FOLDER
	@unset MXMAKE_SCRIPTS_FOLDER
	@unset MXMAKE_CONFIG_FOLDER
endef

FILES_TARGET:=$(SENTINEL_FOLDER)/files.sentinel
$(FILES_TARGET): $(PROJECT_CONFIG) $(VENV_TARGET)
	@echo "Create project files"
	$(call set_files_env,$(VENV_FOLDER),$(SCRIPTS_FOLDER),$(CONFIG_FOLDER))
	@$(VENV_SCRIPTS)mxdev -n -c $(PROJECT_CONFIG)
	$(call unset_files_env,$(VENV_FOLDER),$(SCRIPTS_FOLDER),$(CONFIG_FOLDER))
	@touch $(FILES_TARGET)

.PHONY: files
files: $(FILES_TARGET)

.PHONY: files-dirty
files-dirty:
	@rm -f $(FILES_TARGET)

.PHONY: files-clean
files-clean: files-dirty
	$(call set_files_env,$(VENV_FOLDER),$(SCRIPTS_FOLDER),$(CONFIG_FOLDER))
	@test -e $(VENV_SCRIPTS)mxmake && \
		$(VENV_SCRIPTS)mxmake clean -c $(PROJECT_CONFIG)
	$(call unset_files_env,$(VENV_FOLDER),$(SCRIPTS_FOLDER),$(CONFIG_FOLDER))
	@rm -f constraints-mxdev.txt requirements-mxdev.txt

##############################################################################
# sources
##############################################################################

SOURCES_TARGET:=$(SENTINEL_FOLDER)/sources.sentinel
$(SOURCES_TARGET): $(FILES_TARGET)
	@echo "Checkout project sources"
	@$(VENV_SCRIPTS)mxdev -o -c $(PROJECT_CONFIG)
	@touch $(SOURCES_TARGET)

.PHONY: sources
sources: $(SOURCES_TARGET)

.PHONY: sources-dirty
sources-dirty:
	@rm -f $(SOURCES_TARGET)

.PHONY: sources-clean
sources-clean: sources-dirty
	@rm -rf sources

##############################################################################
# install
##############################################################################

INSTALLED_PACKAGES=.installed.txt

INSTALL_TARGET:=$(SENTINEL_FOLDER)/install.sentinel
$(INSTALL_TARGET): $(SOURCES_TARGET)
	@echo "Install python packages"
	@$(VENV_SCRIPTS)pip install -r requirements-mxdev.txt
	@$(VENV_SCRIPTS)pip freeze > $(INSTALLED_PACKAGES)
	@touch $(INSTALL_TARGET)

.PHONY: install
install: $(INSTALL_TARGET)

.PHONY: install-dirty
install-dirty:
	@rm -f $(INSTALL_TARGET)

##############################################################################
# test
##############################################################################

.PHONY: test
test: $(FILES_TARGET) $(SOURCES_TARGET) $(INSTALL_TARGET) $(TEST_DEPENDENCY_TARGETS)
	@echo "Run tests"
	@test -z "$(TEST_COMMAND)" && echo "No test command defined"
	@test -z "$(TEST_COMMAND)" || bash -c "$(TEST_COMMAND)"

##############################################################################
# coverage
##############################################################################

coverage-install: venv
	@echo "Install Coverage"
	@$(VENV_SCRIPTS)pip install -U coverage

.PHONY: coverage
coverage: $(FILES_TARGET) $(SOURCES_TARGET) $(INSTALL_TARGET) coverage-install
	@echo "Run coverage"
	@test -z "$(COVERAGE_COMMAND)" && echo "No coverage command defined"
	@test -z "$(COVERAGE_COMMAND)" || bash -c "$(COVERAGE_COMMAND)"

.PHONY: coverage-clean
coverage-clean:
	@rm -rf .coverage htmlcov

##############################################################################
# clean
##############################################################################

.PHONY: clean
clean: files-clean venv-clean docs-clean coverage-clean
	@rm -rf $(CLEAN_TARGETS) .mxmake-sentinels .installed.txt

.PHONY: full-clean
full-clean: clean sources-clean

.PHONY: runtime-clean
runtime-clean:
	@echo "Remove runtime artifacts, like byte-code and caches."
	@find . -name '*.py[c|o]' -delete
	@find . -name '*~' -exec rm -f {} +
	@find . -name '__pycache__' -exec rm -fr {} +

##############################################################################
# docs
##############################################################################

docs-install: venv
	@echo "Install Sphinx"
	@$(VENV_SCRIPTS)pip install -U sphinx sphinx-autobuild $(DOCS_REQUIREMENTS)

.PHONY: docs
docs: docs-install
	@echo "Build sphinx docs"
	@test -e $(DOCS_BIN) && $(DOCS_BIN) $(DOCS_SOURCE_FOLDER) $(DOCS_TARGET_FOLDER)
	@test -e $(DOCS_BIN) || echo "Sphinx binary not exists"

.PHONY: docs-live
docs-live: docs-install
	@echo "Rebuild Sphinx documentation on changes, with live-reload in the browser"
	@test -e $(DOCS_AUTOBUILD_BIN) && $(DOCS_AUTOBUILD_BIN) $(DOCS_SOURCE_FOLDER) $(DOCS_TARGET_FOLDER)
	@test -e $(DOCS_AUTOBUILD_BIN) || echo "Sphinx autobuild binary not exists"

.PHONY: docs-clean
docs-clean:
	@rm -rf $(DOCS_TARGET_FOLDER)

##############################################################################
# system dependencies
##############################################################################

.PHONY: system-dependencies
system-dependencies:
	@echo "Install system dependencies"
	@test -z "$(SYSTEM_DEPENDENCIES)" && echo "No System dependencies defined"
	@test -z "$(SYSTEM_DEPENDENCIES)" \
		|| sudo apt-get install -y $(SYSTEM_DEPENDENCIES)

##############################################################################
#: core.base
#: core.venv
#: core.files
#: core.sources
#: core.install
#: core.test
#: core.coverage
#: core.clean
#: core.docs
#: core.system-dependencies
##############################################################################