#:[proxy]
#:title = Proxy targets
#:description = This domain includes proxy targets which are configured in
#:  `mx.ini`. It is expected that defined folder(s) contains a Makefile which
#:  is generated by `mxmake` and this Makefile contains the domains for which
#:  proxy targets are created. The proxy configuration in the `mx.ini` file
#:  looks as follows:
#:
#:  ```ini
#:  mxmake-templates = proxy
#:
#:  [mxmake-proxy]
#:  foldername =
#:      applications:plone,zest-releaser
#:      i18n:*
#:  ```
#:
#:  Each setting in the `mxmake-proxy` section defines a child folder. The
#:  value contains the topic name and the desired domains as comma
#:  separated list. Wildcard `*` means to include all domains of this topic.
#:  Topic and domains are colon separated.
#:
#:depends = core.mxfiles

##############################################################################
# proxy
##############################################################################

-include $(MXMAKE_FILES)/proxy.mk
